import * as React from 'react';
import "../assets/css/main.css";
import LoginSvg from '../assets/images/Logo.svg';

export default function TermsCondition() {
    return (

        <div>
            <section id="main" className="alt align-left" style={{ background: '#f1f1f1', padding: '10px', boxShadow: '0px 0px 10px #ddd', marginBottom: '30px' }}>
                <div className="inner"><img src={LoginSvg} alt="Drivn Fintech" width={80} /></div>
            </section>
            <section id="main">
                <div className="inner">
                    <div className="about-company block text  ">
                        <p className="title">Drivn Fintech Sdn bhd Check App Terms of Service (For End User)
                        </p><div className="content"><p style={{ textAlign: 'left' }}><span style={{ color: '#000000' }}>Welcome to Drivn Fintech Sdn bhd Terms of Service! Drivn Fintech Sdn bhd Ltd. (“<strong>Drivn Fintech Sdn bhd</strong>”, “<strong>we</strong>” or “<strong>us</strong>”) offers several wellness services and solutions which, amongst others, measure and display various vital signs indicators of its users. Please read these terms of services (these “<strong>Terms</strong>”) carefully as they govern your use of the Drivn Fintech Sdn bhd Services (as defined below) and create a binding contract between you and Drivn Fintech Sdn bhd.</span></p>
                            <ol style={{ textAlign: 'left' }}>
                                <li><span style={{ color: '#000000' }}><strong>The Services</strong></span></li>
                            </ol>
                            <p style={{ paddingLeft: '40px', textAlign: 'left' }}><span style={{ color: '#000000' }}>These Terms govern the use of Drivn Fintech Sdn bhd’s services (the “<strong>Services</strong>”), which provided through Binah Check application, as updated from time to time (the “<strong>Application</strong>”).</span></p>
                            <p style={{ paddingLeft: '40px', textAlign: 'left' }}><span style={{ color: '#000000' }}>YOU MUST ACCEPT THESE TERMS IN ORDER TO LOGGING INTO THE APPLICATION AND IN ORDER TO USE IT. BY DOWNLOADING THE APPLICATION, YOU ACCEPT THESE TERMS, AND THESE TERMS SHALL BE EFFECTIVE AS OF THE EARLIEST OCCURRENCE OF SUCH EVENTS (THE “<strong>EFFECTIVE DATE</strong>”). IF YOU DO NOT ACCEPT THESE TERMS, DO NOT LOGGING INTO THE APPLICATION.</span></p>
                            <ol style={{ textAlign: 'left' }} start={2}>
                                <li><span style={{ color: '#000000' }}><strong>Your Drivn Fintech Sdn bhd Account</strong></span></li>
                            </ol>
                            <p style={{ paddingLeft: '40px', textAlign: 'left' }}><span style={{ color: '#000000' }}>Use of the Services is not permitted to individuals under the age of 18. You are responsible for all activity that occurs in association with your account. Drivn Fintech Sdn bhd is not liable for any Loss (as defined below) caused by your failure to maintain the confidentiality of your account credentials.</span></p>
                            <ol style={{ textAlign: 'left' }} start={3}>
                                <li><span style={{ color: '#000000' }}><strong>Your Information</strong></span></li>
                            </ol>
                            <p style={{ paddingLeft: '40px', textAlign: 'left' }}><span style={{ color: '#000000' }}>Any information or data submitted by you through the Services or collected by the Services with respect to you (including without limitation your e-mail address, weight, Hight and gender) (collectively, “<strong>Information</strong>”) may be used, stored and transferred by Drivn Fintech Sdn bhd in accordance with its privacy polic (the “<strong>Privacy Policy</strong>”). We encourage you to review the Privacy Policy, as it is an integral part of these Terms. Except as expressly set forth otherwise under these Terms, you are solely responsible for all Information you provide.</span></p>
                            <p style={{ paddingLeft: '40px', textAlign: 'left' }}><span style={{ color: '#000000' }}>Without derogating from the generality of the foregoing, whereas you are using the Services pursuant to the invitation from, or subject to a license purchased by, an Organization (“<strong>Organizational User/S</strong>”), you acknowledge that the Organizational User which invited you or purchased your license will have access through the Services to all or parts of the Information related to you. When you use the Services pursuant to such license or invitation, you consent to the sharing of your Information with the applicable Organizational User, and to the use by such Organizational User of such Information in the manners permitted herein and otherwise for its legitimate business purposes. While Drivn Fintech Sdn bhd requires of its Organizational Users to abide by requirements substantially similar to those of the Privacy Policy and by applicable law, Drivn Fintech Sdn bhd cannot (and do not) ensure such compliance and such Organizational User alone is liable for its behavior. Thus, Drivn Fintech Sdn bhd has no liability in this respect thereto.</span></p>
                            <ol style={{ textAlign: 'left' }} start={4}>
                                <li><span style={{ color: '#000000' }}><strong>Your Obligations</strong></span></li>
                            </ol>
                            <p style={{ paddingLeft: '40px', textAlign: 'left' }}><span style={{ color: '#000000' }}>Amongst other requirements of these Terms, you are required to comply in all respects with the instructions related to the use of Drivn Fintech Sdn bhd Services specified in the documentation posted on Drivn Fintech Sdn bhd website: <em>Drivn Fintech Sdn bhd</em> (the “<strong>Website</strong>”) or the Application (the “<strong>Documentation</strong>”), including without limitation, our Privacy Policy and other requirements related to the equipment required for use of the Services (which may include, without limitation, a supported mobile device and adequate internet access). You are solely responsible for the consequences of your failure to comply with the instructions of the Documentation.</span></p>
                            <ol style={{ textAlign: 'left' }} start={5}>
                                <li><span style={{ color: '#000000' }}><strong>License</strong></span></li>
                            </ol>
                            <p style={{ paddingLeft: '40px', textAlign: 'left' }}><span style={{ color: '#000000' }}>Drivn Fintech Sdn bhd grants you a limited, revocable, non-exclusive, non-transferable, non-sublicensable license, subject to these Terms, to install, access and use the Services through the Application.</span></p>
                            <p style={{ textAlign: 'left' }}><span style={{ color: '#000000' }}><strong>&nbsp;</strong></span></p>
                            <ol style={{ textAlign: 'left' }} start={6}>
                                <li><span style={{ color: '#000000' }}><strong>Prohibited Uses</strong></span></li>
                            </ol>
                            <p style={{ paddingLeft: '40px', textAlign: 'left' }}><span style={{ color: '#000000' }}>Notwithstanding anything to the contrary herein, you may not perform, attempt to perform, or encourage or assist others in performing any of the following: (i) connecting to or accessing any portion of the Services other than through the use of the Services’ intended interfaces; ; (ii) accessing non-public areas of the Services; (iii) testing the vulnerability of the Services, breaching any security or authentication measures, circumventing any technological measure implemented by Drivn Fintech Sdn bhd or any of its providers to protect the Services, or publishing or disseminating any reports or analysis with respect to the Services; (iv) decompiling, disassembling, reverse engineering, tampering with, or attempting to derive the source code of any portion of the Services; (v) copying, adapting, modifying, preparing derivative works based upon the Services, Drivn Fintech Sdn bhd Materials or Drivn Fintech Sdn bhd Analysis; or (vi) distributing, licensing, selling, transferring, publicly displaying, publicly performing, transmitting or otherwise disposing of the Services, Drivn Fintech Sdn bhd Materials, Drivn Fintech Sdn bhd Analysis or any portion thereof in a manner not explicitly permitted herein.</span></p>
                            <ol style={{ textAlign: 'left' }} start={7}>
                                <li><span style={{ color: '#000000' }}><strong>Maintenance and Support</strong></span></li>
                            </ol>
                            <p style={{ paddingLeft: '40px', textAlign: 'left' }}><span style={{ color: '#000000' }}>Drivn Fintech Sdn bhd shall use commercially reasonable efforts to make the Services available at all times except as set forth in Drivn Fintech Sdn bhd’s services level agreement (the “<strong>SLA</strong>”).</span></p>
                            <ol style={{ textAlign: 'left' }} start={8}>
                                <li><span style={{ color: '#000000' }}><strong>Disclaimers; Use at Own Risk</strong></span></li>
                            </ol>
                            <p style={{ paddingLeft: '40px', textAlign: 'left' }}><span style={{ color: '#000000' }}>OTHER THAN TO THE EXTENT SPECIFICALLY AND EXPLICITLY SPECIFIED IN THESE TERMS OR THE DOCUMENTATION, THE SERVICES, AND THE Drivn Fintech Sdn bhd MATERIALS ARE PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND. WITHOUT LIMITING THE FOREGOING, WE EXPLICITLY DISCLAIM ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT. ANY WARRANTY PROVIDED IN THE DOCUMENTATION SHALL NOT APPLY TO THE EXTENT (A) THE SERVICES ARE USED IN A MANNER WHICH IS NOT COMPLIANT WITH THESE TERMS, THE DOCUMENTATION AND/OR ANY OTHER APPLICABLE TERMS, INCLUDING IN PARTICULAR AND WITHOUT LIMITATION TO THE EXTENT THE SERVICES HAVE BEEN MODIFIED, CHANGED, OR REPAIRED BY ANY PARTY WHICH IS NOT Drivn Fintech Sdn bhd.</span></p>
                            <p style={{ paddingLeft: '40px', textAlign: 'left' }}><span style={{ color: '#000000' }}>Drivn Fintech Sdn bhd makes no warranty regarding the accuracy and completeness of any statistics, parameters, data or information monitored and/or displayed through any of the Services (“<strong>Drivn Fintech Sdn bhd Analysis</strong>”). The Services and the Drivn Fintech Sdn bhd Analysis are not intended to diagnose, treat, monitor, cure, or prevent any disease, and are not intended to match or replace (a) any services or information produced by medical or scientific measurement devices; and/or (b) any diagnosis by you or your physicians of consumption of medication or any other medical parameters; and/or (c) any services or treatments by physicians and other medical care professionals. Additionally, Drivn Fintech Sdn bhd makes no warranty that the Services will meet your requirements and/or any medical or regulatory standards or be available on an uninterrupted, secure, or error-free basis. You acknowledge and agree that if you rely on any Services, including without limitation the Drivn Fintech Sdn bhd Analysis, you do so solely at your own risk.</span></p>
                            <p style={{ paddingLeft: '40px', textAlign: 'left' }}><span style={{ color: '#000000' }}>We do not accept liability for any error or omission, injury, expense, loss (including, without limitation, loss of the Drivn Fintech Sdn bhd Analysis) or damage caused, in whole or in part, by you or any other third party’s actions, omissions, or negligence.</span></p>
                            <p style={{ paddingLeft: '40px', textAlign: 'left' }}><span style={{ color: '#000000' }}>Without derogating from the aforementioned, you acknowledge that the Services may be impaired or produce inaccurate or incorrect output (including without limitation Drivn Fintech Sdn bhd Analysis) due to, without limitation (a) the provision by you of incorrect details; and/or (b) use of the Application when it is not updated with the last available update and/or (c) use of the Application other than as instructed by Drivn Fintech Sdn bhd.</span></p>
                            <ol style={{ textAlign: 'left' }} start={9}>
                                <li><span style={{ color: '#000000' }}><strong>Limitation of Liability</strong></span></li>
                            </ol>
                            <p style={{ paddingLeft: '40px', textAlign: 'left' }}><span style={{ color: '#000000' }}>NEITHER Drivn Fintech Sdn bhd, ITS AFFILIATES, OFFICERS AND/OR EMPLOYEES SHALL BE LIABLE FOR (A) ANY INCIDENTAL, SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES, COSTS, LOSSES OR EXPENSES INCLUDING WITHOUT LIMITATION LOSS OF PROFITS, DATA AND/OR GOODWILL ARISING OUT OF, OR IN CONNECTION WITH, THE SERVICES AND/OR YOUR OR ANY THIRD PARTY’S RELIANCE UPON THE SERVICES (INCLUDING WITHOUT LIMITATION THE Drivn Fintech Sdn bhd ANALYSIS); AND (B) ANY DAMAGES, LOSSES AND/OR EXPENSES (“<strong>LOSSES</strong>”) ARISING OUT OF, OR IN CONNECTION WITH&nbsp; YOUR OR ANY THIRD PARTY’S RELIANCE UPON THE Drivn Fintech Sdn bhd SERVICES (INCLUDING WITHOUT LIMITATION THE Drivn Fintech Sdn bhd ANALYSIS). THE AFOREMENTIONED SHALL APPLY REGARDLESS OF WHETHER A CLAIM IS BASED UPON CONTRACT, TORT (INCLUDING WITHOUT LIMITATION NEGLIGENCE) OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT Drivn Fintech Sdn bhd HAS BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE, EVEN IF A LIMITED REMEDY SET FORTH HEREIN IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PURPOSE. THE EXCLUSIONS AND LIMITATIONS OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN Drivn Fintech Sdn bhd AND YOU.</span></p>
                            <p style={{ paddingLeft: '40px', textAlign: 'left' }}><span style={{ color: '#000000' }}>WITHOUT DEROGATING FROM THE ABOVE, Drivn Fintech Sdn bhd SHALL HAVE NO LIABILITY WHATSOEVER FOR ANY INACCURACY, PERFORMANCE FAILURES, BREACHES, UNAVAILABILITY AND/OR LOSSES ARISING OUT OF, OR IN CONNECTION WITH, ANY EXTERNAL THIRD PARTY SERVICES UPON WHICH THE SERVICES RELY (INCLUDING WITHOUT LIMITATION FAILURES RELATED TO HOSTING SERVICES, PAYMENT PROCESSING SERVICES) AND/OR GENERALLY FROM CAUSES BEYOND Drivn Fintech Sdn bhd’S REASONABLE CONTROL, INCLUDING, BUT NOT LIMITED TO, CELLULAR, INTERNET OR BLUETOOTH FAILURE, NETWORK OR COMPUTER EQUIPMENT FAILURES, ELECTRICAL POWER FAILURES, OR ACTS OF PROVIDERS OF THIRD PARTY SERVICES.</span></p>
                            <p style={{ paddingLeft: '40px', textAlign: 'left' }}><span style={{ color: '#000000' }}>IN ADDITION, IN ANY EVENT AND NOTWITHSTANDING ANYTHING HEREIN TO THE CONTRARY INCLUDING THE FOREGOING, TO THE MAXIMUM EXTENT PERMITTED BY LAW, BINAH’S MAXIMUM TOTAL AGGREGATE LIABILITY UNDER THESE TERMS WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY OR OTHERWISE, SHALL NOT EXCEED, IN THE AGGREGATE FOR ALL CLAIMS, USD 1,000.</span></p>
                            <ol style={{ textAlign: 'left' }} start={10}>
                                <li><span style={{ color: '#000000' }}><strong>Indemnity</strong></span></li>
                            </ol>
                            <p style={{ paddingLeft: '40px', textAlign: 'left' }}><span style={{ color: '#000000' }}>You will indemnify and hold harmless Drivn Fintech Sdn bhd, its affiliates and their respective officers and/or employees, from and against any Losses (for clarification, the term Losses shall include without limitation reasonable attorney fees) incurred due to any third party suit, claim or procedure arising out of, or connected with your breach of these Terms.</span></p>
                            <ol style={{ textAlign: 'left' }} start={11}>
                                <li><span style={{ color: '#000000' }}><strong>Drivn Fintech Sdn bhd’s Rights</strong></span></li>
                            </ol>
                            <p style={{ paddingLeft: '40px', textAlign: 'left' }}><span style={{ color: '#000000' }}>Drivn Fintech Sdn bhd retains all right, title and interest, including without limitation all patents, copyrights, trade secrets, trademarks, and any other intellectual property rights (whether or not registerable) in and to the Services, the Drivn Fintech Sdn bhd Materials and the technology, know how, and any other intellectual property (including without limitation any software) underlying the Services, including without limitation any improvements, updates, upgrades, error-corrections or other modifications thereto, and any derivative work based thereon. Except for the rights expressly granted to you hereunder, these Terms do not grant you any rights or license by implication or otherwise with respect to any of Drivn Fintech Sdn bhd’s Materials and/or its intellectual property, including Drivn Fintech Sdn bhd Analysis. The term “<strong>Drivn Fintech Sdn bhd Materials</strong>” shall mean any names, texts, graphics, images, music, audio, video, works of authorship, names, and symbols of any kind, and information or other materials that are generated, displayed on, provided or otherwise made available through the Services.</span></p>
                            <p style={{ paddingLeft: '40px', textAlign: 'left' }}><span style={{ color: '#000000' }}>Without derogating from the above, as between you and Drivn Fintech Sdn bhd, Drivn Fintech Sdn bhd shall be the sole and exclusive owner of all rights to any and all feedback provided by you, and any ideas, inventions and/or improvements (whether protectable by any intellectual property protection or not) conceived or derived or resulting from such feedback or embodied therein (“<strong>Feedback</strong>”). You hereby irrevocably assign to Drivn Fintech Sdn bhd any rights that you may have in such Feedback, and to the extent such rights may not be assigned, you hereby provide Drivn Fintech Sdn bhd a royalty free, perpetual, worldwide, exclusive, irrevocable license to use such Feedback for any purpose, including commercial purposes.</span></p>
                            <ol style={{ textAlign: 'left' }} start={12}>
                                <li><span style={{ color: '#000000' }}><strong>Termination</strong></span></li>
                            </ol>
                            <p style={{ paddingLeft: '40px', textAlign: 'left' }}><span style={{ color: '#000000' }}>These Terms shall be effective as of the Effective Date and shall continue in effect until they are terminated as specified herein.</span></p>
                            <p style={{ paddingLeft: '40px', textAlign: 'left' }}><span style={{ color: '#000000' }}>You may terminate these Terms and all outstanding Services (and their Subscription Periods) by submitting a request to delete your Account or providing written notice of termination to Drivn Fintech Sdn bhd and then ceasing all use of the Services, in which case these Terms and the applicable Services shall terminate immediately upon deletion or receipt of termination notice by Drivn Fintech Sdn bhd (as applicable). Drivn Fintech Sdn bhd may, in its sole discretion, terminate these Terms and/or cease providing the Services or any portion thereof: (i) at any time for convenience or inability to continue providing the Services with an advance 30 day written notice, or (ii) in the event that your agreement with the Organizational User has been terminated for whatever reason.</span></p>
                            <p style={{ paddingLeft: '40px', textAlign: 'left' }}><span style={{ color: '#000000' }}>Upon termination or expiration of these Terms, for any reason whatsoever, all rights granted to you shall immediately terminate and you shall immediately cease any use of the Services.</span></p>
                            <p style={{ paddingLeft: '40px', textAlign: 'left' }}><span style={{ color: '#000000' }}>You acknowledge that following termination, any Information related or made available to you through the Services will no longer be available to you through the Services or otherwise made available to you by Drivn Fintech Sdn bhd (and Drivn Fintech Sdn bhd shall be entitled to destroy such information or data).</span></p>
                            <p style={{ paddingLeft: '40px', textAlign: 'left' }}><span style={{ color: '#000000' }}>Notwithstanding the forgoing, any provisions of these Terms that by their nature are intended to survive termination, including without limitation the provisions of sections ‎8, ‎9, ‎10, ‎11, ‎12, ‎13 and ‎18 of the Terms, shall not be affected or prejudiced by such termination.</span></p>
                            <ol style={{ textAlign: 'left' }} start={13}>
                                <li><span style={{ color: '#000000' }}><strong><u>Confidential Information</u></strong></span></li>
                            </ol>
                            <p style={{ paddingLeft: '40px', textAlign: 'left' }}><span style={{ color: '#000000' }}>Both Drivn Fintech Sdn bhd and you agree to keep confidential and to use only for purposes of performing or as otherwise permitted under these Terms, any proprietary or confidential information of the other party disclosed pursuant to these Terms which is marked as confidential or is identified at the time of disclosure as confidential or which would reasonably be considered confidential or proprietary in nature (“<strong>Confidential</strong> <strong>Information</strong>”). The obligation of confidentiality shall not apply to information which (i) is publicly available through authorized disclosure; or (ii) is known by the receiving party at the time of disclosure as evidenced in writing; or (iii) is rightfully obtained from a third party who has the right to disclose it; or (iv) which is required by law, government order or request to be disclosed (provided that the receiving party shall give written notice to the other party prior to such disclosure and an opportunity, at the objecting party’s expense, to take legal steps to resist or narrow such request). Without derogating from the aforesaid, you acknowledge and agree that the Services and any of Drivn Fintech Sdn bhd Materials shall be deemed to constitute Confidential Information of Drivn Fintech Sdn bhd. The receiving party will use no less than a reasonable standard of care to safeguard the Confidential Information received from the disclosing party.&nbsp; The receiving party will only use the Confidential Information of the disclosing party: (a) to exercise its rights and perform its obligations under this Agreement, or (b) as otherwise required by law. Upon any termination of these Terms, either you or Drivn Fintech Sdn bhd shall destroy or return to the other party (as applicable) all its Confidential Information, and all copies thereof, in the possession, custody or control of the party unless otherwise expressly provided in these Terms. The parties agree that the receiving party’s disclosure of Confidential Information except as provided herein may result in irreparable injury for which a remedy in money damages may be inadequate. The parties further agree that in the event of such disclosure or threatened disclosure, the disclosing party may be entitled to seek an injunction to prevent the breach or threatened breach, in addition to remedies otherwise available to the disclosing party at law or in equity.</span></p>
                            <ol style={{ textAlign: 'left' }} start={14}>
                                <li><span style={{ color: '#000000' }}><strong>Alerts and Notifications</strong></span></li>
                            </ol>
                            <p style={{ paddingLeft: '40px', textAlign: 'left' }}><span style={{ color: '#000000' }}>As part of your use of the Services, you may receive notifications, text messages, alerts, or e-mails. You hereby agree to the receipt of these communications. You can control receipt of related communications from your account settings, unless required for operational purposes.</span></p>
                            <ol style={{ textAlign: 'left' }} start={15}>
                                <li><span style={{ color: '#000000' }}><strong>Changes </strong></span></li>
                            </ol>
                            <p style={{ paddingLeft: '40px', textAlign: 'left' }}><span style={{ color: '#000000' }}>We are entitled to change these Terms from time to time. We will notify you of changes to the Terms by posting them on the Website and/or the Application or in any other way we deem appropriate. Any such change shall be effective immediately upon such notification or posting (as applicable). By continuing to use the Services following a change, you are accepting such change. We may also change or discontinue, temporarily or permanently, any feature or component of the Drivn Fintech Sdn bhd Services at any time, with or without notice, without incurring any liability to you aside from as explicitly specified herein.</span></p>
                            <ol style={{ textAlign: 'left' }} start={16}>
                                <li><span style={{ color: '#000000' }}><strong>Force Majeure</strong></span></li>
                            </ol>
                            <p style={{ paddingLeft: '40px', textAlign: 'left' }}><span style={{ color: '#000000' }}>Neither party shall be liable to the other for any performance delay or failure to perform hereunder (other than any payment obligation) due to any act, omission or condition beyond the reasonable control of the affected party.</span></p>
                            <ol style={{ textAlign: 'left' }} start={17}>
                                <li><span style={{ color: '#000000' }}><strong>Governing Law and Venue</strong></span></li>
                            </ol>
                            <p style={{ paddingLeft: '40px', textAlign: 'left' }}><span style={{ color: '#000000' }}>If you are located in the Americas, these Terms shall be governed by the laws of the State of Delaware, without regard to its conflict or choice of laws principles. The parties irrevocably agree that any and all disputes concerning these Terms shall be brought in the federal and state courts of the state of Delaware having jurisdiction thereof and irrevocably waive any and all claims and defenses either might otherwise have in any such action or proceeding in any of such courts based upon any alleged lack of personal jurisdiction, improper venue, forum, non-convenience or any similar claim or defense.</span></p>
                            <p style={{ paddingLeft: '40px', textAlign: 'left' }}><span style={{ color: '#000000' }}>If you are located in the rest of the world (excluding the Americas), these Terms shall be construed and enforced in all respects in accordance with the laws of the State of Israel, without reference to principles of conflict or choice of law. The courts located in the Tel-Aviv District of the State of Israel shall have exclusive jurisdiction over any dispute or matter in connection with these Terms.</span></p>
                            <ol style={{ textAlign: 'left' }} start={18}>
                                <li><span style={{ color: '#000000' }}><strong>General Terms</strong></span></li>
                            </ol>
                            <p style={{ paddingLeft: '40px', textAlign: 'left' }}><span style={{ color: '#000000' }}>The headings used in these Terms are for convenience of reference only and shall not affect the interpretation or meaning of the terms and provisions of these Terms. These Terms constitute the entire agreement between the parties regarding the use of the Services (other than to the extent explicitly specified herein), and supersede any previous arrangement, understanding or agreement between you and Drivn Fintech Sdn bhd, written or oral, relating thereto. Neither party’s waiver of any breach or default of any provision of this Terms shall constitute a waiver of other provisions or any other right hereunder, or a waiver of any subsequent breach or default. Unless expressly provided otherwise herein, all remedies hereunder are cumulative and do not exclude any other remedies available by law. If any provision of these Terms is found by any court or administrative body of competent jurisdiction to be invalid, unenforceable or illegal, the other provisions shall remain in full force and effect. These Terms do not confer any rights on any third party. You shall not, without the prior written consent of Drivn Fintech Sdn bhd, assign, transfer, or sub-contract these Terms and/or any of your rights or obligations under these Terms, and any unauthorized assignment shall be null and void. Drivn Fintech Sdn bhd may, at any time, freely assign, transfer or sub-contract these Terms or any or all of its rights or obligations under these Terms.</span></p>
                            <p style={{ paddingLeft: '40px', textAlign: 'left' }}><span style={{ color: '#000000' }}><strong>&nbsp;</strong></span></p>
                            <ol style={{ textAlign: 'left' }} start={19}>
                                <li><span style={{ color: '#000000' }}><strong>Contact Details</strong></span></li>
                            </ol>
                            <p style={{ paddingLeft: '40px', textAlign: 'left' }}><span style={{ color: '#000000' }}>Any required or permitted notices hereunder must be given in writing (a) if to Drivn Fintech Sdn bhd, by E-mail to the following address: <a style={{ color: '#000000' }} href="mailto:support@Drivn Fintech Sdn bhd">support@Drivn Fintech Sdn bhd</a>; and (b) if to you by e-mail to the e-mail address with which you registered for the Drivn Fintech Sdn bhd Services. Notices will be deemed received within 1 business day in the region of Drivn Fintech Sdn bhd’s operation.</span></p>
                            <p style={{ textAlign: 'left' }}><span style={{ color: '#000000' }}>These Terms were last updated on: May 18, 2022</span></p>
                            <p style={{ textAlign: 'left' }}>
                            </p></div>
                    </div></div></section>
        </div>
    )

}